/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

Object.defineProperty(exports, "__esModule", { value: true });
var _uniqueId = require('@bit/nexxtway.react-rainbow.libs.unique-id');
exports.uniqueId = _uniqueId && _uniqueId.hasOwnProperty('default') ? _uniqueId.default : _uniqueId;